apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-kafka-project-backend
  labels:
    app: kafka-project-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka-project-backend
  template:
    metadata:
      labels:
        app: kafka-project-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: kafka-project-backend
      containers:
        - name: kafka-project-backend
          image: manvinderjit/kafka-project-backend:v4
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
          readinessProbe:
            httpGet:
              path: /api/events
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /api/events
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
