apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: default
data:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "${MSK_BOOTSTRAP_BROKERS}"
  SPRING_DATASOURCE_URL: "jdbc:mysql://${RDS_ENDPOINT}:${RDS_PORT}/${DB_NAME}?createDatabaseIfNotExist=true"
  SPRING_DATASOURCE_USERNAME: "${DB_USERNAME}"
