apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-kafka-project-frontend
  labels:
    app: kafka-project-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka-project-frontend
  template:
    metadata:
      labels:
        app: kafka-project-frontend
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: kafka-project-frontend
      containers:
        - name: kafka-project-frontend
          image: manvinderjit/kafka-project-frontend:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: frontend-config
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 25
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
