apiVersion: v1
kind: Service
metadata:
  name: service-kafka-project-frontend
  labels:
    app: kafka-project-frontend
spec:
  type: NodePort
  selector:
    app: kafka-project-frontend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30080
