apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: default
data:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "${MSK_BOOTSTRAP_BROKERS}"
  SPRING_APPLICATION_NAME: "frontend"
  BACKEND_API_URL: "http://service-kafka-project-backend:8080/api/events"