apiVersion: v1
kind: Service
metadata:
  name: service-kafka-project-backend
  labels:
    app: kafka-project-backend
spec:
  selector:
    app: kafka-project-backend
  ports:
    - protocol: TCP
      port: 8080        
      targetPort: 8080  
