apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: default
data:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "YOUR_KAFKA_BOOTSTRAP_SERVERS"
  SPRING_DATASOURCE_URL: "jdbc:mysql://YOUR_RDS_ENDPOINT:3306/YOUR_DATABASE_NAME?createDatabaseIfNotExist=true"
  SPRING_DATASOURCE_USERNAME: "YOUR_DB_USERNAME"
