name: Deploy a three-tier app and infrastructure using docker and ecr

on:
  push:
    paths:
      - 'three-tier-infra-app-docker-ecr/**'
    branches:
      - 'project/3-tier-infra-app-docker-ecr'

  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform Action'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

# These permissions are needed to interact with GitHub's OIDC Token endpoint.
permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}  

jobs:
  build_push_base_alpine_java_image:    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4        
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TERRAFORM_GITHUB_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image to ECR
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION_TERRA: ${{ secrets.AWS_REGION_TERRA }}          
          IMAGE_TAG: v1
        run: |
          IMAGE_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION_TERRA}.amazonaws.com/aws-terra-projects/base-alpine-java:${IMAGE_TAG}
          docker build -t $IMAGE_URI three-tier-infra-app-docker-ecr/docker-files/base-alpine-java
          docker push $IMAGE_URI

  deploy:        
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: three-tier-infra-app-docker-ecr

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TERRAFORM_GITHUB_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.2"

      - name: Terraform Format
        id: fmt
        if: ${{ github.event_name == 'push' || github.event.inputs.action == 'apply' }}
        run: terraform fmt -check
        continue-on-error: true
        
      - name: Terraform Init
        id: init        
        env:
          AWS_TFSTATE_BUCKET_KEY_NAME : ${{ secrets.AWS_TFSTATE_BUCKET_KEY_NAME }}
          AWS_TFSTATE_BUCKET_NAME: ${{ secrets.AWS_TFSTATE_BUCKET_NAME }}
        run: terraform init -backend-config="bucket=${AWS_TFSTATE_BUCKET_NAME}" -backend-config="key=three-tier-infra-app-docker-ecr/${AWS_TFSTATE_BUCKET_KEY_NAME}"
        
      - name: Terraform Validate
        id: validate
        if: ${{ github.event_name == 'push' || github.event.inputs.action == 'apply' }}
        run: terraform validate -no-color
      
      - name: Terraform Plan
        id: plan
        if: ${{ github.event_name == 'push' || github.event.inputs.action == 'apply' }}
        run: terraform plan -out=tfplan -no-color -no-color -var="ec2_ami_id=${{ env.AMI_ID }}" -var="db_name=${{ secrets.AWS_THREE_TIER_RDS_DB_NAME }}" -var="db_username=${{ secrets.AWS_THREE_TIER_RDS_DB_USER_NAME }}" -var="db_password=${{ secrets.AWS_THREE_TIER_RDS_DB_PASSWORD }}"

      - name: Terraform Apply
        id: apply
        if: ${{ github.event_name == 'push' || github.event.inputs.action == 'apply' }}
        run: terraform apply -auto-approve tfplan

      - name: Terraform Destroy
        id: destroy
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy' }}
        run: terraform destroy -auto-approve
      